
import java.awt.Dimension;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nilton
 */
public class puzzleMain extends javax.swing.JFrame{
    MenuPuzzles mP;
    ImageIcon iSKT1;
    ImageIcon [] original;
    ImageIcon []actual=new ImageIcon[16];
    int contador;
    public int posJugador;
    public Cliente cliente;
    
    /**
     * Creates new form puzzleMain
     */
    public puzzleMain() {
        try{
            initComponents();
            this.setMinimumSize(new Dimension(500, 521));
            setLocationRelativeTo(null);
            setResizable(false);
            jMenuItem3.setEnabled(false);
            cliente=new Cliente(this);         
            Thread hilo = new Thread(cliente);
            hilo.start();
        }catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mis Jugadas:");

        jLabel3.setText("Jugadas contrincante:");

        jMenu1.setText("Opciones");

        jMenuItem2.setText("Seleccionar Campeon");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Jugar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        mP = new MenuPuzzles();
        mP.setVisible(true);
        jMenuItem3.setEnabled(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    private boolean win(){
        boolean respuesta=false;
        this.rellenarActual();
        for(int i=0;i<actual.length;i++){
            if(actual[i]==original[i]){
                respuesta=true;
            }
            else{
                respuesta=false;
                break;
            }
        }
        return respuesta;
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        contador=0;
        original=mP.campeonSeleccionado();
        iSKT1=original[15]; 
        int numeroRandom;
        Vector guardaPos=new Vector();
        while(guardaPos.size()<16){
            numeroRandom=(int)(Math.random()*16);
            if(guardaPos.indexOf(numeroRandom)<0){
                guardaPos.add(numeroRandom);
            }
            else{
                continue;
            }
        }
        /*
        jButton1.setIcon(original[0]);
        jButton2.setIcon(original[1]);
        jButton3.setIcon(original[2]);
        jButton4.setIcon(original[3]);
        jButton5.setIcon(original[4]);
        jButton6.setIcon(original[5]);
        jButton7.setIcon(original[6]);
        jButton8.setIcon(original[7]);
        jButton9.setIcon(original[8]);
        jButton10.setIcon(original[9]);
        jButton11.setIcon(original[10]);
        jButton12.setIcon(original[11]);
        jButton13.setIcon(original[12]);
        jButton14.setIcon(original[13]);
        jButton15.setIcon(original[14]);
        jButton16.setIcon(original[15]);
        */
        jButton1.setIcon(original[(int)guardaPos.get(0)]);
        jButton2.setIcon(original[(int)guardaPos.get(1)]);
        jButton3.setIcon(original[(int)guardaPos.get(2)]);
        jButton4.setIcon(original[(int)guardaPos.get(3)]);
        jButton5.setIcon(original[(int)guardaPos.get(4)]);
        jButton6.setIcon(original[(int)guardaPos.get(5)]);
        jButton7.setIcon(original[(int)guardaPos.get(6)]);
        jButton8.setIcon(original[(int)guardaPos.get(7)]);
        jButton9.setIcon(original[(int)guardaPos.get(8)]);
        jButton10.setIcon(original[(int)guardaPos.get(9)]);
        jButton11.setIcon(original[(int)guardaPos.get(10)]);
        jButton12.setIcon(original[(int)guardaPos.get(11)]);
        jButton13.setIcon(original[(int)guardaPos.get(12)]);
        jButton14.setIcon(original[(int)guardaPos.get(13)]);
        jButton15.setIcon(original[(int)guardaPos.get(14)]);
        jButton16.setIcon(original[(int)guardaPos.get(15)]);
       // this.rellenarActual();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton1.getIcon();
        ImageIcon focus1=(ImageIcon)jButton2.getIcon();
        ImageIcon focus2=(ImageIcon)jButton5.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton1.setIcon(iSKT1);
            jButton2.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton1.setIcon(iSKT1);
           jButton5.setIcon(target); 
        } 
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton2.getIcon();
        ImageIcon focus1=(ImageIcon)jButton1.getIcon();
        ImageIcon focus2=(ImageIcon)jButton3.getIcon();
        ImageIcon focus3=(ImageIcon)jButton6.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton2.setIcon(iSKT1);
            jButton1.setIcon(target);  
        }
        else if(focus2==iSKT1){
           jButton2.setIcon(iSKT1);
           jButton3.setIcon(target); 
        }
        
        else if(focus3==iSKT1){
           jButton2.setIcon(iSKT1);
           jButton6.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton3.getIcon();
        ImageIcon focus1=(ImageIcon)jButton2.getIcon();
        ImageIcon focus2=(ImageIcon)jButton4.getIcon();
        ImageIcon focus3=(ImageIcon)jButton7.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton3.setIcon(iSKT1);
            jButton2.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton3.setIcon(iSKT1);
           jButton4.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton3.setIcon(iSKT1);
           jButton7.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton4.getIcon();
        ImageIcon focus1=(ImageIcon)jButton3.getIcon();
        ImageIcon focus2=(ImageIcon)jButton8.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton4.setIcon(iSKT1);
            jButton3.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton4.setIcon(iSKT1);
           jButton8.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton5.getIcon();
        ImageIcon focus1=(ImageIcon)jButton1.getIcon();
        ImageIcon focus2=(ImageIcon)jButton6.getIcon();
        ImageIcon focus3=(ImageIcon)jButton9.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton5.setIcon(iSKT1);
            jButton1.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton5.setIcon(iSKT1);
           jButton6.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton5.setIcon(iSKT1);
           jButton9.setIcon(target); 
        }   
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton6.getIcon();
        ImageIcon focus1=(ImageIcon)jButton2.getIcon();
        ImageIcon focus2=(ImageIcon)jButton5.getIcon();
        ImageIcon focus3=(ImageIcon)jButton7.getIcon();
        ImageIcon focus4=(ImageIcon)jButton10.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton6.setIcon(iSKT1);
            jButton2.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton6.setIcon(iSKT1);
           jButton5.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton6.setIcon(iSKT1);
           jButton7.setIcon(target); 
        }else if(focus4==iSKT1){
           jButton6.setIcon(iSKT1);
           jButton10.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton7.getIcon();
        ImageIcon focus1=(ImageIcon)jButton3.getIcon();
        ImageIcon focus2=(ImageIcon)jButton6.getIcon();
        ImageIcon focus3=(ImageIcon)jButton8.getIcon();
        ImageIcon focus4=(ImageIcon)jButton11.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton7.setIcon(iSKT1);
            jButton3.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton7.setIcon(iSKT1);
           jButton6.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton7.setIcon(iSKT1);
           jButton8.setIcon(target); 
        }else if(focus4==iSKT1){
           jButton7.setIcon(iSKT1);
           jButton11.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton8.getIcon();
        ImageIcon focus1=(ImageIcon)jButton4.getIcon();
        ImageIcon focus2=(ImageIcon)jButton7.getIcon();
        ImageIcon focus3=(ImageIcon)jButton12.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton8.setIcon(iSKT1);
            jButton4.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton8.setIcon(iSKT1);
           jButton7.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton8.setIcon(iSKT1);
           jButton12.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton9.getIcon();
        ImageIcon focus1=(ImageIcon)jButton5.getIcon();
        ImageIcon focus2=(ImageIcon)jButton10.getIcon();
        ImageIcon focus3=(ImageIcon)jButton13.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton9.setIcon(iSKT1);
            jButton5.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton9.setIcon(iSKT1);
           jButton10.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton9.setIcon(iSKT1);
           jButton13.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton10.getIcon();
        ImageIcon focus1=(ImageIcon)jButton6.getIcon();
        ImageIcon focus2=(ImageIcon)jButton9.getIcon();
        ImageIcon focus3=(ImageIcon)jButton11.getIcon();
        ImageIcon focus4=(ImageIcon)jButton14.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton10.setIcon(iSKT1);
            jButton6.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton10.setIcon(iSKT1);
           jButton9.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton10.setIcon(iSKT1);
           jButton11.setIcon(target); 
        }else if(focus4==iSKT1){
           jButton10.setIcon(iSKT1);
           jButton14.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton11.getIcon();
        ImageIcon focus1=(ImageIcon)jButton7.getIcon();
        ImageIcon focus2=(ImageIcon)jButton10.getIcon();
        ImageIcon focus3=(ImageIcon)jButton12.getIcon();
        ImageIcon focus4=(ImageIcon)jButton15.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton11.setIcon(iSKT1);
            jButton7.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton11.setIcon(iSKT1);
           jButton10.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton11.setIcon(iSKT1);
           jButton12.setIcon(target); 
        }else if(focus4==iSKT1){
           jButton11.setIcon(iSKT1);
           jButton15.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton12.getIcon();
        ImageIcon focus1=(ImageIcon)jButton8.getIcon();
        ImageIcon focus2=(ImageIcon)jButton11.getIcon();
        ImageIcon focus3=(ImageIcon)jButton16.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton12.setIcon(iSKT1);
            jButton8.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton12.setIcon(iSKT1);
           jButton11.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton12.setIcon(iSKT1);
           jButton16.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton13.getIcon();
        ImageIcon focus1=(ImageIcon)jButton9.getIcon();
        ImageIcon focus2=(ImageIcon)jButton14.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton13.setIcon(iSKT1);
            jButton9.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton13.setIcon(iSKT1);
           jButton14.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton14.getIcon();
        ImageIcon focus1=(ImageIcon)jButton10.getIcon();
        ImageIcon focus2=(ImageIcon)jButton13.getIcon();
        ImageIcon focus3=(ImageIcon)jButton15.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton14.setIcon(iSKT1);
            jButton10.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton14.setIcon(iSKT1);
           jButton13.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton14.setIcon(iSKT1);
           jButton15.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton15.getIcon();
        ImageIcon focus1=(ImageIcon)jButton11.getIcon();
        ImageIcon focus2=(ImageIcon)jButton14.getIcon();
        ImageIcon focus3=(ImageIcon)jButton16.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton15.setIcon(iSKT1);
            jButton11.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton15.setIcon(iSKT1);
           jButton14.setIcon(target); 
        }
        else if(focus3==iSKT1){
           jButton15.setIcon(iSKT1);
           jButton16.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        ImageIcon target=(ImageIcon)jButton16.getIcon();
        ImageIcon focus1=(ImageIcon)jButton12.getIcon();
        ImageIcon focus2=(ImageIcon)jButton15.getIcon();
        contador++;
        if(focus1==iSKT1){
            jButton16.setIcon(iSKT1);
            jButton12.setIcon(target);
        }
        else if(focus2==iSKT1){
           jButton16.setIcon(iSKT1);
           jButton15.setIcon(target); 
        }
        jLabel2.setText(String.valueOf(contador));
        boolean win=this.win();
        enviarWin(win,contador);
    }//GEN-LAST:event_jButton16ActionPerformed
    private ImageIcon [] rellenarActual(){
            actual[0]=(ImageIcon)jButton1.getIcon();
            actual[1]=(ImageIcon)jButton2.getIcon();
            actual[2]=(ImageIcon)jButton3.getIcon();
            actual[3]=(ImageIcon)jButton4.getIcon();
            actual[4]=(ImageIcon)jButton5.getIcon();
            actual[5]=(ImageIcon)jButton6.getIcon();
            actual[6]=(ImageIcon)jButton7.getIcon();
            actual[7]=(ImageIcon)jButton8.getIcon();
            actual[8]=(ImageIcon)jButton9.getIcon();
            actual[9]=(ImageIcon)jButton10.getIcon();
            actual[10]=(ImageIcon)jButton11.getIcon();
            actual[11]=(ImageIcon)jButton12.getIcon();
            actual[12]=(ImageIcon)jButton13.getIcon();
            actual[13]=(ImageIcon)jButton14.getIcon();
            actual[14]=(ImageIcon)jButton15.getIcon();
            actual[15]=(ImageIcon)jButton16.getIcon();
            return actual;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puzzleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puzzleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puzzleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puzzleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puzzleMain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables


    void setNombreJugador(String nombre) {
        posJugador=Integer.parseInt(nombre);
        jLabel5.setText("Jugador:"+nombre);
    }
    public void setJugadasContrincante(int numero){
        jLabel4.setText(numero+"");
    }
    public void enviarWin(boolean win, int cont){
        cliente.enviarWin(win,cont,this.posJugador);
    }
}
